### ISSUE TITLE
Androidx - Plugin does not work

### ISSUE THREAD

**Issue by Josephine7** [khirr/Android-Privacy-Policy#2]
I have used this lib with couple of older apps still using support libs. When we migrated to use android x this libs is unusable. the fact that the constructor requires appcompatactivity instead of just activity restricts it to usage with Android support based products which are becoming obsolete. Values in constructor are final therefore it is impossible to create a class and extend from it. 
Are you going to look at redeveloping this to cater for android x based projects ?

**Comment by khirr** [comment]
Hello, thank you for asking, I just updated the library, you can use 1.0.2 version for AndroidX support and 1.0.1 for AppCompat.
