### ISSUE TITLE
Reset acceptance condition

### ISSUE THREAD

**Issue by Enny1991** [khirr/Android-Privacy-Policy#3]
Hi,

Thanks for this great tool! I was wondering if there is a way to reset the status of the `accepted` condition. In case something in the terms changes and we want the user to accept again the terms. 

Cheers,
+Enea

**Comment by khirr** [comment]
Hello, 

Thank you for your feedback, I just updated the project to 1.0.3 version, now you can use forceReset() method, next time you call show() method, accept policies will be required again.
